version: '3'
services: 
  node: 
    build: .
    container_name: react
    environment: 
        - NODE_ENV=production
        - CI=true
#    volumes: 
#      - ./:/usr/src/app
    ports: 
      - '3000:3000'
    tty: true